#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# CPATMX130 configuration
CND_ARTIFACT_DIR_CPATMX130=dist/CPATMX130/production
CND_ARTIFACT_NAME_CPATMX130=CPATMX130.X.production.hex
CND_ARTIFACT_PATH_CPATMX130=dist/CPATMX130/production/CPATMX130.X.production.hex
CND_PACKAGE_DIR_CPATMX130=${CND_DISTDIR}/CPATMX130/package
CND_PACKAGE_NAME_CPATMX130=cpatmx130.x.tar
CND_PACKAGE_PATH_CPATMX130=${CND_DISTDIR}/CPATMX130/package/cpatmx130.x.tar
